default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: flickr_development

test:
  <<: *default
  database: flickr_test

production:
  url: <%= ENV['FLICKR_DATABASE_URL'] %>
